[package]
name = "slang_refl"
version = "0.1.0"
edition = "2024"

[dependencies]
cxx = "1.0"


[build-dependencies]
cmake = "0.1"
cxx-build = "1.0"

[target.wasm32.dependencies]
link-cplusplus = { version = "1", features = ["nothing"] }