[package]
name = "rust-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = {git = "https://github.com/rust-windowing/winit.git", rev = "5199474"}
ash = "0.38.0+1.3.281"
ash-window = "0.13.0"
cxx = "1.0"

[build-dependencies]
cmake = "0.1"
cxx-build = "1.0"
build-print = "1.0"